name: GitVersion
description: ""
outputs:
  Major:
    description: ""
  Minor:
    description: ""
  Patch:
    description: ""
  PreReleaseTag:
    description: ""
  PreReleaseTagWithDash:
    description: ""
  PreReleaseLabel:
    description: ""
  PreReleaseLabelWithDash:
    description: ""
  PreReleaseNumber:
    description: ""
  WeightedPreReleaseNumber:
    description: ""
  BuildMetaData:
    description: ""
  BuildMetaDataPadded:
    description: ""
  FullBuildMetaData:
    description: ""
  MajorMinorPatch:
    description: ""
  SemVer:
    description: ""
  LegacySemVer:
    description: ""
  LegacySemVerPadded:
    description: ""
  AssemblySemVer:
    description: ""
  AssemblySemFileVer:
    description: ""
  FullSemVer:
    description: ""
  InformationalVersion:
    description: ""
  BranchName:
    description: ""
  EscapedBranchName:
    description: ""
  Sha:
    description: ""
  ShortSha:
    description: ""
  NuGetVersionV2:
    description: ""
  NuGetVersion:
    description: ""
  NuGetPreReleaseTagV2:
    description: ""
  NuGetPreReleaseTag:
    description: ""
  VersionSourceSha:
    description: ""
  CommitsSinceVersionSource:
    description: ""
  CommitsSinceVersionSourcePadded:
    description: ""
  UncommittedChanges:
    description: ""
  CommitDate:
    description: ""

runs:
  using: composite
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Run GitVersion
      shell: sh
      run: |
        python ${{ github.action_path }}/gitversion.py
