name: GitVersion
description: ""
outputs:
  Major:
    description: ""
    value: ${{ steps.gitversion.outputs.Major }}
  Minor:
    description: ""
    value: ${{ steps.gitversion.outputs.Minor }}
  Patch:
    description: ""
    value: ${{ steps.gitversion.outputs.Patch }}
  PreReleaseTag:
    description: ""
    value: ${{ steps.gitversion.outputs.PreReleaseTag }}
  PreReleaseTagWithDash:
    description: ""
  PreReleaseLabel:
    description: ""
  PreReleaseLabelWithDash:
    description: ""
  PreReleaseNumber:
    description: ""
  WeightedPreReleaseNumber:
    description: ""
  BuildMetaData:
    description: ""
  BuildMetaDataPadded:
    description: ""
  FullBuildMetaData:
    description: ""
  MajorMinorPatch:
    description: ""
  SemVer:
    description: ""
    value: ${{ steps.gitversion.outputs.SemVer }}
  LegacySemVer:
    description: ""
  LegacySemVerPadded:
    description: ""
  AssemblySemVer:
    description: ""
  AssemblySemFileVer:
    description: ""
  FullSemVer:
    description: ""
  InformationalVersion:
    description: ""
  BranchName:
    description: ""
  EscapedBranchName:
    description: ""
  Sha:
    description: ""
    value: ${{ steps.gitversion.outputs.Sha }}
  ShortSha:
    description: ""
  NuGetVersionV2:
    description: ""
  NuGetVersion:
    description: ""
  NuGetPreReleaseTagV2:
    description: ""
  NuGetPreReleaseTag:
    description: ""
  VersionSourceSha:
    description: ""
  CommitsSinceVersionSource:
    description: ""
  CommitsSinceVersionSourcePadded:
    description: ""
  UncommittedChanges:
    description: ""
  CommitDate:
    description: ""

runs:
  using: composite
  steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - id: gitversion
      name: Run GitVersion
      shell: sh
      run: |
        python ${{ github.action_path }}/gitversion.py ${{ github.workspace }}
